### ISSUE TITLE
Passing additional information to collection

### ISSUE THREAD

**Issue by martimpassos** [giacomomarchioro/pyIIIFpres#16]
Hi Giacomo, I see [here](https://github.com/giacomomarchioro/pyIIIFpres/blob/117c4d793b512c2282175a78a82c0b0760762243/IIIFpres/iiifpapi3.py#L1910) that you're only removing `items` from manifests that are added to a collection. The specification states that 

> Collections or Manifests [referenced](https://iiif.io/api/presentation/3.0/#12-terminology) in the items property must have the id, type and label properties. They should have the thumbnail property.

Is there any use in keeping `metadata`, `provider` and other properties in the collection? Isn't this data fetched by clients by dereferencing the manifest URI?

**Comment by giacomomarchioro** [comment]
Hi Martim, I also agree with you, initially, I forced the user to use the [refManifest class](https://github.com/giacomomarchioro/pyIIIFpres/blob/117c4d793b512c2282175a78a82c0b0760762243/IIIFpres/iiifpapi3.py#L1819) however speaking with the consortium it turned out that  sometimes user might want to preserve part of the metadata in the collections, (I can't remember why, maybe for avoiding multiple requests?).

Eventually discussing it with the consortium I modified the schema for allowing this feature https://github.com/IIIF/presentation-validator/commit/4f750747b1998587b7c734411f36ccd4a89875fe.

However, of course you can make a workaround to it:

```python
from IIIFpres import iiifpapi3 
collection = iiifpapi3.Collection()
man = iiifpapi3.Manifest()
## after setting all methods
cman = collection.add_manifest_to_items()
cman.id = man.id
cman.label = man.label
```

**Comment by martimpassos** [comment]
Got it! I don't care about the extra info there, besides polluting the reading a bit. I'll keep things how they are.
